import type { Metadata } from "next"
import { Toaster } from "sonner"
import "../styles/globals.css"
import { Providers } from "@/components/providers"
import { geistMono, geistSans } from "@/styles/fonts"

export const metadata: Metadata = {
    title: "Healthcare System",
    description: "Generated by create next app"
}

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <Providers>
                    {children}
                    <Toaster richColors position="top-center" />
                </Providers>
            </body>
        </html>
    )
}
